### ISSUE TITLE
PNG Type 

### ISSUE THREAD

**Issue by sghazagh** [bradtraversy/mongo_file_uploads#1]
Hi Brad,
Many thanks for this tutorial.
I just have realized that the line 127 in "app.js" file is:

`if (file.contentType === 'image/jpeg' || file.contentType === 'img/png') {`

should be fixed to:

`if (file.contentType === 'image/jpeg' || file.contentType === 'image/png') {
`

The type is "image/png" and not "img/png"otherwise it will not show the PNG type images after upload.

Thanks

**Comment by bradtraversy** [comment]
You are right, sorry about that, Ill fix it
